services:
  bitcoin-indexer:
    build: .
    ports:
      - "8332:8332"  # Bitcoin RPC port
    environment:
      - RPC_USER=${RPC_USER}
      - RPC_PASSWORD=${RPC_PASSWORD}
      - RPC_URL=${RPC_URL}
      - MONGO_URI=mongodb://mongodb:27017/
      - USE_REDIS=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - mongodb
      - redis
    extra_hosts:
      - "umbrel.local:192.168.0.193"
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: unless-stopped
    container_name: bitcoin-indexer

  mongodb:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    ports:
      - "27050:27017" # Expose the MongoDB port outside the container at 27050
    container_name: mongodb
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  redis_data: